[package]
name = "sundial-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "sundial"
path = "src/main.rs"

[dependencies]
sundial-core.workspace = true
sundial-mps.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
pollster.workspace = true
